### ISSUE TITLE
Contao 4 Compatibility

### ISSUE THREAD

**Issue by swisschris** [aschempp/contao-previewdownload#6]
Es scheint, als würden sich verschiedene Interessenten an einer Realisierung finanziell beteiligen. Liesse sich dafür ein Preis in die Runde werfen?

https://community.contao.org/de/showthread.php?50898-Download-mit-Vorschau-Preview&p=481889#post481889

**Comment by aschempp** [comment]
Nicht auf GitHub, dazu bitte eine E-Mail schreiben (info@terminal42.ch)

**Comment by swisschris** [comment]
Hallo Andreas

Ich bin nur einer Empfehlung gefolgt – und kenne GitHub eigentlich nicht, ausser wenn mich die Suche nach der Lösung eines Problems dorthin führt. 

Dann also per Mail: Was meinst du, wäre eine Contao-4-Kompatibilität für Previewdownload oder etwas in dieser Richtung möglich? Seit ich mit Contao arbeite, suche ich nach so etwas und habe Previewdownload hin und wieder verwendet. Eine eigene, ausgereifte und umfassende Erweiterung wäre natürlich perfekt – Stellenausschreibungen, Prospekte, Menukarten sind klassische Anwendungsmöglichkeiten. 

Wir bzw. unsere Kunden haben schon mehrere Male die Entwicklung einer Erweiterung gesponsert – wie teuer käme sowas?


Freundliche Grüsse

Christian Tschui
Media Creator | Beratung + Realisation

jaeggi & tschui grafik webdesign gmbh
bolacker 12 | 4563 gerlafingen | 032 675 05 02
christian@jaeggitschui.ch | www.jaeggitschui.ch


Am 17. September 2018 um 08:44:55, Andreas Schempp (notifications@github.com) schrieb:

Nicht auf GitHub, dazu bitte eine E-Mail schreiben (info@terminal42.ch)

**Comment by aschempp** [comment]
Tjanun, die Mail kam nicht an mich sondern an GitHub 😂
